version: '2'

services:
    web:
        build:
            context: ./
            dockerfile: deploy/web.docker
        volumes:
            - ./:/var/www
        ports:
            - "80:80"
        links:
            - app
            - database
            
    app:
        build:
            context: ./
            dockerfile: deploy/app.docker
        volumes:
            - ./:/var/www
        links:
            - database

    database:
        image: mariadb:latest
        restart: always
        volumes:
            - ./mysql:/var/lib/mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=lunch
            - MYSQL_PASSWORD=lunch
            - MYSQL_USER=lunch
            - MYSQL_DATABASE=lunchinator
        ports:
            - "3306:3306"
