version: '2'

services:
    web:
        build:
            context: ./
            dockerfile: deploy/web.docker
        volumes:
            - ./:/var/www
        ports:
            - "8080:80"
        links:
            - app
            
    app:
        build:
            context: ./
            dockerfile: deploy/app.docker
        volumes:
            - ./:/var/www
        links:
            - database
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"

    database:
        image: mariadb:latest
        restart: always
        volumes:
            - ./mysql:/var/lib/mysql
        restart: always
        environment:
            - "MYSQL_ROOT_PASSWORD=lunch"
            - "MYSQL_DATABASE=lunchinator"
        ports:
            - "33061:3306"
